[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.13"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.13"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.13"
